/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "echo.h"
#include <stdio.h>
#include <stdlib.h> /* getenv, exit */


void
echo_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	int  add_1_arg;

#ifndef	DEBUG
	clnt = clnt_create(host, ECHO_PROG, ECHO_VERS, "netpath");
	if (clnt == (CLIENT *) NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
#endif	/* DEBUG */

	add_1_arg=3;
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror(clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy(clnt);
#endif		/* DEBUG */

	printf("result=%d\n",*result_1);

}


main(int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf("usage:  %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	echo_prog_1(host);
}
