/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ECHO_H_RPCGEN
#define	_ECHO_H_RPCGEN

#include <rpc/rpc.h>

#ifdef __cplusplus
extern "C" {
#endif


#define	ECHO_PROG ((unsigned long)(0x31111111))
#define	ECHO_VERS ((unsigned long)(1))

#if defined(__STDC__) || defined(__cplusplus)
#define	ADD ((unsigned long)(1))
extern  int * add_1(int *, CLIENT *);
extern  int * add_1_svc(int *, struct svc_req *);
extern int echo_prog_1_freeresult(SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define	ADD ((unsigned long)(1))
extern  int * add_1();
extern  int * add_1_svc();
extern int echo_prog_1_freeresult();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ECHO_H_RPCGEN */
